# Generated by Django 3.2.12 on 2022-07-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_year', models.SmallIntegerField(verbose_name='CurrentYear')),
                ('current_month', models.SmallIntegerField(verbose_name='CurrentMonth')),
                ('current_day', models.SmallIntegerField(verbose_name='CurrentDay')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(verbose_name='Year')),
                ('month', models.SmallIntegerField(verbose_name='Month')),
                ('day', models.SmallIntegerField(verbose_name='Day')),
            ],
        ),
    ]
