# Generated by Django 4.0.5 on 2022-11-02 19:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)], verbose_name='Number')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('folkname', models.CharField(blank=True, max_length=64, verbose_name='Folkname')),
                ('is_oneday', models.BooleanField(verbose_name='IsOneday')),
                ('is_leap_month', models.BooleanField(verbose_name='IsLeapMonth')),
            ],
        ),
        migrations.CreateModel(
            name='YearData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(validators=[django.core.validators.RegexValidator('^-?[1-9]\\d{0,3}$', 'Year must be not zero and between -9999 and 9999')], verbose_name='Number')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Number')),
                ('time', models.TimeField(verbose_name='Time')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('is_suggested', models.BooleanField(verbose_name='IsSuggested')),
                ('is_only_for_gm', models.BooleanField(verbose_name='IsOnlyForGm')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faerun_calendar.monthdata')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faerun_calendar.yeardata')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_day', models.SmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Number')),
                ('current_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faerun_calendar.monthdata')),
                ('current_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faerun_calendar.yeardata')),
            ],
        ),
    ]
