# Generated by Django 3.2.12 on 2022-07-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faerun_calendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(unique=True, verbose_name='Number')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('folkname', models.CharField(max_length=64, unique=True, verbose_name='Folkname')),
            ],
        ),
    ]
