# Generated by Django 3.2.12 on 2022-07-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faerun_calendar', '0002_monthdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=0, max_length=2500, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=0, verbose_name='Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default=0, max_length=250, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
