# Generated by Django 3.2.12 on 2022-07-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faerun_calendar', '0003_auto_20220713_1117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarData',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='MonthData',
        ),
    ]
