# Generated by Django 4.0.5 on 2022-11-02 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faerun_calendar', '0004_event_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='month',
        ),
        migrations.RemoveField(
            model_name='event',
            name='year',
        ),
        migrations.DeleteModel(
            name='CalendarData',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='MonthData',
        ),
        migrations.DeleteModel(
            name='YearData',
        ),
    ]
