# Generated by Django 3.2.12 on 2022-07-13 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faerun_calendar', '0005_calendardata_event_monthdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarData',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='MonthData',
        ),
    ]
