# Generated by Django 3.2.12 on 2022-07-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faerun_calendar', '0006_auto_20220713_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_year', models.SmallIntegerField(verbose_name='CurrentYear')),
                ('current_month', models.SmallIntegerField(verbose_name='CurrentMonth')),
                ('current_day', models.SmallIntegerField(verbose_name='CurrentDay')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(verbose_name='Year')),
                ('month', models.SmallIntegerField(verbose_name='Month')),
                ('day', models.SmallIntegerField(verbose_name='Day')),
                ('time', models.TimeField(verbose_name='Time')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description', models.TextField(max_length=2500, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='MonthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(unique=True, verbose_name='Number')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('folkname', models.CharField(max_length=64, unique=True, verbose_name='Folkname')),
            ],
        ),
    ]
