# Generated by Django 3.2.12 on 2022-07-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faerun_calendar', '0007_calendardata_event_monthdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthdata',
            name='folkname',
            field=models.CharField(max_length=64, verbose_name='Folkname'),
        ),
    ]
