# Generated by Django 3.2.12 on 2022-07-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faerun_calendar', '0008_alter_monthdata_folkname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthdata',
            name='folkname',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='Folkname'),
        ),
    ]
