# Generated by Django 3.2.12 on 2022-07-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faerun_calendar', '0011_monthdata_is_oneday'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendardata',
            name='leap_month',
            field=models.SmallIntegerField(default=11, verbose_name='LeapMonth'),
            preserve_default=False,
        ),
    ]
