# Generated by Django 3.2.12 on 2022-07-14 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faerun_calendar', '0012_calendardata_leap_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendardata',
            name='current_month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faerun_calendar.monthdata'),
        ),
    ]
