# Generated by Django 3.2.12 on 2022-07-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faerun_calendar', '0014_auto_20220714_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daydata',
            name='month',
        ),
        migrations.RemoveField(
            model_name='daydata',
            name='year',
        ),
        migrations.RemoveField(
            model_name='event',
            name='day',
        ),
        migrations.DeleteModel(
            name='CalendarData',
        ),
        migrations.DeleteModel(
            name='DayData',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='MonthData',
        ),
        migrations.DeleteModel(
            name='YearData',
        ),
    ]
