# Generated by Django 3.2.12 on 2022-07-14 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faerun_calendar', '0015_auto_20220714_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(unique=True, verbose_name='Number')),
            ],
        ),
        migrations.CreateModel(
            name='MonthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(unique=True, verbose_name='Number')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('folkname', models.CharField(blank=True, max_length=64, verbose_name='Folkname')),
                ('is_oneday', models.BooleanField(verbose_name='IsOneday')),
                ('is_leap_month', models.BooleanField(verbose_name='IsLeapMonth')),
            ],
        ),
        migrations.CreateModel(
            name='YearData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(verbose_name='Year')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Time')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description', models.TextField(max_length=2500, verbose_name='Description')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faerun_calendar.daydata')),
            ],
        ),
        migrations.AddField(
            model_name='daydata',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faerun_calendar.monthdata'),
        ),
        migrations.AddField(
            model_name='daydata',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faerun_calendar.yeardata'),
        ),
        migrations.CreateModel(
            name='CalendarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faerun_calendar.daydata')),
            ],
        ),
    ]
