# Generated by Django 3.2.12 on 2022-07-14 13:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faerun_calendar', '0017_auto_20220714_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendardata',
            name='current_month',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faerun_calendar.monthdata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendardata',
            name='current_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faerun_calendar.yeardata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='current_month',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faerun_calendar.monthdata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='current_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faerun_calendar.yeardata'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendardata',
            name='current_day',
            field=models.SmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.SmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Number'),
        ),
        migrations.DeleteModel(
            name='DayData',
        ),
    ]
