# Generated by Django 3.2.12 on 2022-07-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faerun_calendar', '0018_auto_20220714_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='current_month',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='current_year',
            new_name='year',
        ),
    ]
