# Generated by Django 3.2.12 on 2022-11-01 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faerun_calendar', '0019_auto_20220714_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Number'),
        ),
    ]
