# Generated by Django 3.2.12 on 2022-11-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faerun_calendar', '0020_alter_event_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_only_for_gm',
            field=models.BooleanField(default=False, verbose_name='IsOnlyForGm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='is_suggested',
            field=models.BooleanField(default=False, verbose_name='IsSuggested'),
            preserve_default=False,
        ),
    ]
