# Generated by Django 3.2.12 on 2022-07-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250, verbose_name='URL')),
                ('text', models.CharField(max_length=250, verbose_name='Text')),
            ],
        ),
    ]
